version: '2'
services:
  database:
    image: mysql:5.7
    volumes:
      - ../DatabaseData/:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=gfu_test"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33061:3306"
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "4000:80"
    depends_on:
      - database
    links:
      - database:database
volumes:
  dbdata: